//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesManagementSystem.SubCatServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BLLSubCategory", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BLLSubCategory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int SubCatIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubCatNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubCatDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CatNameField;
        
        private int CatIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SubCatID {
            get {
                return this.SubCatIDField;
            }
            set {
                if ((this.SubCatIDField.Equals(value) != true)) {
                    this.SubCatIDField = value;
                    this.RaisePropertyChanged("SubCatID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SubCatName {
            get {
                return this.SubCatNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SubCatNameField, value) != true)) {
                    this.SubCatNameField = value;
                    this.RaisePropertyChanged("SubCatName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SubCatDescription {
            get {
                return this.SubCatDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.SubCatDescriptionField, value) != true)) {
                    this.SubCatDescriptionField = value;
                    this.RaisePropertyChanged("SubCatDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CatName {
            get {
                return this.CatNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CatNameField, value) != true)) {
                    this.CatNameField = value;
                    this.RaisePropertyChanged("CatName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int CatID {
            get {
                return this.CatIDField;
            }
            set {
                if ((this.CatIDField.Equals(value) != true)) {
                    this.CatIDField = value;
                    this.RaisePropertyChanged("CatID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SubCatServices.SubCatServiceSoap")]
    public interface SubCatServiceSoap {
        
        // CODEGEN: Generating message contract since element name subCat from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertSubCat", ReplyAction="*")]
        SalesManagementSystem.SubCatServices.InsertSubCatResponse InsertSubCat(SalesManagementSystem.SubCatServices.InsertSubCatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertSubCat", ReplyAction="*")]
        System.Threading.Tasks.Task<SalesManagementSystem.SubCatServices.InsertSubCatResponse> InsertSubCatAsync(SalesManagementSystem.SubCatServices.InsertSubCatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteSubCat", ReplyAction="*")]
        void DeleteSubCat(int subCatId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteSubCat", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteSubCatAsync(int subCatId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllSubCat", ReplyAction="*")]
        void GetAllSubCat();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllSubCat", ReplyAction="*")]
        System.Threading.Tasks.Task GetAllSubCatAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSubCatById", ReplyAction="*")]
        void GetSubCatById(int subCatId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSubCatById", ReplyAction="*")]
        System.Threading.Tasks.Task GetSubCatByIdAsync(int subCatId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCategories", ReplyAction="*")]
        void GetCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCategories", ReplyAction="*")]
        System.Threading.Tasks.Task GetCategoriesAsync();
        
        // CODEGEN: Generating message contract since element name subCat from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSubCat", ReplyAction="*")]
        SalesManagementSystem.SubCatServices.UpdateSubCatResponse UpdateSubCat(SalesManagementSystem.SubCatServices.UpdateSubCatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSubCat", ReplyAction="*")]
        System.Threading.Tasks.Task<SalesManagementSystem.SubCatServices.UpdateSubCatResponse> UpdateSubCatAsync(SalesManagementSystem.SubCatServices.UpdateSubCatRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertSubCatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertSubCat", Namespace="http://tempuri.org/", Order=0)]
        public SalesManagementSystem.SubCatServices.InsertSubCatRequestBody Body;
        
        public InsertSubCatRequest() {
        }
        
        public InsertSubCatRequest(SalesManagementSystem.SubCatServices.InsertSubCatRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertSubCatRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SalesManagementSystem.SubCatServices.BLLSubCategory subCat;
        
        public InsertSubCatRequestBody() {
        }
        
        public InsertSubCatRequestBody(SalesManagementSystem.SubCatServices.BLLSubCategory subCat) {
            this.subCat = subCat;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertSubCatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertSubCatResponse", Namespace="http://tempuri.org/", Order=0)]
        public SalesManagementSystem.SubCatServices.InsertSubCatResponseBody Body;
        
        public InsertSubCatResponse() {
        }
        
        public InsertSubCatResponse(SalesManagementSystem.SubCatServices.InsertSubCatResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertSubCatResponseBody {
        
        public InsertSubCatResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSubCatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSubCat", Namespace="http://tempuri.org/", Order=0)]
        public SalesManagementSystem.SubCatServices.UpdateSubCatRequestBody Body;
        
        public UpdateSubCatRequest() {
        }
        
        public UpdateSubCatRequest(SalesManagementSystem.SubCatServices.UpdateSubCatRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateSubCatRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SalesManagementSystem.SubCatServices.BLLSubCategory subCat;
        
        public UpdateSubCatRequestBody() {
        }
        
        public UpdateSubCatRequestBody(SalesManagementSystem.SubCatServices.BLLSubCategory subCat) {
            this.subCat = subCat;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSubCatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSubCatResponse", Namespace="http://tempuri.org/", Order=0)]
        public SalesManagementSystem.SubCatServices.UpdateSubCatResponseBody Body;
        
        public UpdateSubCatResponse() {
        }
        
        public UpdateSubCatResponse(SalesManagementSystem.SubCatServices.UpdateSubCatResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateSubCatResponseBody {
        
        public UpdateSubCatResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SubCatServiceSoapChannel : SalesManagementSystem.SubCatServices.SubCatServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubCatServiceSoapClient : System.ServiceModel.ClientBase<SalesManagementSystem.SubCatServices.SubCatServiceSoap>, SalesManagementSystem.SubCatServices.SubCatServiceSoap {
        
        public SubCatServiceSoapClient() {
        }
        
        public SubCatServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SubCatServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubCatServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubCatServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SalesManagementSystem.SubCatServices.InsertSubCatResponse SalesManagementSystem.SubCatServices.SubCatServiceSoap.InsertSubCat(SalesManagementSystem.SubCatServices.InsertSubCatRequest request) {
            return base.Channel.InsertSubCat(request);
        }
        
        public void InsertSubCat(SalesManagementSystem.SubCatServices.BLLSubCategory subCat) {
            SalesManagementSystem.SubCatServices.InsertSubCatRequest inValue = new SalesManagementSystem.SubCatServices.InsertSubCatRequest();
            inValue.Body = new SalesManagementSystem.SubCatServices.InsertSubCatRequestBody();
            inValue.Body.subCat = subCat;
            SalesManagementSystem.SubCatServices.InsertSubCatResponse retVal = ((SalesManagementSystem.SubCatServices.SubCatServiceSoap)(this)).InsertSubCat(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SalesManagementSystem.SubCatServices.InsertSubCatResponse> SalesManagementSystem.SubCatServices.SubCatServiceSoap.InsertSubCatAsync(SalesManagementSystem.SubCatServices.InsertSubCatRequest request) {
            return base.Channel.InsertSubCatAsync(request);
        }
        
        public System.Threading.Tasks.Task<SalesManagementSystem.SubCatServices.InsertSubCatResponse> InsertSubCatAsync(SalesManagementSystem.SubCatServices.BLLSubCategory subCat) {
            SalesManagementSystem.SubCatServices.InsertSubCatRequest inValue = new SalesManagementSystem.SubCatServices.InsertSubCatRequest();
            inValue.Body = new SalesManagementSystem.SubCatServices.InsertSubCatRequestBody();
            inValue.Body.subCat = subCat;
            return ((SalesManagementSystem.SubCatServices.SubCatServiceSoap)(this)).InsertSubCatAsync(inValue);
        }
        
        public void DeleteSubCat(int subCatId) {
            base.Channel.DeleteSubCat(subCatId);
        }
        
        public System.Threading.Tasks.Task DeleteSubCatAsync(int subCatId) {
            return base.Channel.DeleteSubCatAsync(subCatId);
        }
        
        public void GetAllSubCat() {
            base.Channel.GetAllSubCat();
        }
        
        public System.Threading.Tasks.Task GetAllSubCatAsync() {
            return base.Channel.GetAllSubCatAsync();
        }
        
        public void GetSubCatById(int subCatId) {
            base.Channel.GetSubCatById(subCatId);
        }
        
        public System.Threading.Tasks.Task GetSubCatByIdAsync(int subCatId) {
            return base.Channel.GetSubCatByIdAsync(subCatId);
        }
        
        public void GetCategories() {
            base.Channel.GetCategories();
        }
        
        public System.Threading.Tasks.Task GetCategoriesAsync() {
            return base.Channel.GetCategoriesAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SalesManagementSystem.SubCatServices.UpdateSubCatResponse SalesManagementSystem.SubCatServices.SubCatServiceSoap.UpdateSubCat(SalesManagementSystem.SubCatServices.UpdateSubCatRequest request) {
            return base.Channel.UpdateSubCat(request);
        }
        
        public void UpdateSubCat(SalesManagementSystem.SubCatServices.BLLSubCategory subCat) {
            SalesManagementSystem.SubCatServices.UpdateSubCatRequest inValue = new SalesManagementSystem.SubCatServices.UpdateSubCatRequest();
            inValue.Body = new SalesManagementSystem.SubCatServices.UpdateSubCatRequestBody();
            inValue.Body.subCat = subCat;
            SalesManagementSystem.SubCatServices.UpdateSubCatResponse retVal = ((SalesManagementSystem.SubCatServices.SubCatServiceSoap)(this)).UpdateSubCat(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SalesManagementSystem.SubCatServices.UpdateSubCatResponse> SalesManagementSystem.SubCatServices.SubCatServiceSoap.UpdateSubCatAsync(SalesManagementSystem.SubCatServices.UpdateSubCatRequest request) {
            return base.Channel.UpdateSubCatAsync(request);
        }
        
        public System.Threading.Tasks.Task<SalesManagementSystem.SubCatServices.UpdateSubCatResponse> UpdateSubCatAsync(SalesManagementSystem.SubCatServices.BLLSubCategory subCat) {
            SalesManagementSystem.SubCatServices.UpdateSubCatRequest inValue = new SalesManagementSystem.SubCatServices.UpdateSubCatRequest();
            inValue.Body = new SalesManagementSystem.SubCatServices.UpdateSubCatRequestBody();
            inValue.Body.subCat = subCat;
            return ((SalesManagementSystem.SubCatServices.SubCatServiceSoap)(this)).UpdateSubCatAsync(inValue);
        }
    }
}
